import type {
  ConditionDefinition,
  FieldType,
  FixedTemplateDefinition,
  TemplateFieldDefinition,
} from './types';

const procurementCondition: ConditionDefinition = { field: 'hasProcurement', equals: true };
const financingCondition: ConditionDefinition = { field: 'hasFinancing', equals: true };

const GUIDANCE = {
  D21: '明确商机渠道方、商务关系与客情关系；商机来源可为自拓、高层、展会或渠道。',
  D22: '说明项目立项背景、必要性和政策支持。',
  D23: '说明每一级客户评级、资金方、项目阶段、上下游签署状态、付款节奏及我司签约方。',
  D24: '说明资金方、财政拨款或自筹等资金来源、行政审批和资金落实情况。',
  D25: '说明项目提供内容、付款方式/节奏/账期，以及验收交付和服务期限。',
  D26: '说明合同额、净销售额、税率和项目全口径毛利率。',
  D27: '区分技术外包与外采软硬件，说明采购内容、原因和预算。',
  D28: '说明指定供应商情况、能力资质、大型企业属性及商务部确认情况。',
  D29: '说明采购金额、税率、方式，以及付款/交付/验收/售后/违约是否完全背靠背。',
  D30: '说明垫资金额、成本、原因，以及上下游付款时间、账期和付款方式。',
} as const;

function field(
  key: string,
  label: string,
  section: string,
  type: FieldType,
  required: boolean,
  question: string,
  targetCells: string[] = [],
  requiredWhen?: ConditionDefinition,
  guidance?: string,
): TemplateFieldDefinition {
  return { key, label, section, type, required, question, targetCells, requiredWhen, guidance };
}

export const PREAUDIT_TEMPLATE_2025_11: FixedTemplateDefinition = {
  id: 'preaudit-2025-11',
  version: '2025-11',
  name: '域外合同前置审批表-2025年11月启用',
  token: 'preaudit202511',
  fileName: 'preaudit-2025-11.xlsx',
  sheetName: '域外合同前置审批表-2025年11月启用',
  anchors: { B2: '域外合同前置特批审批表', B49: '后台部门建议' },
  riskCells: {
    customerCredit: 'G8',
    contractChain: 'G9',
    paymentTerms: 'G10',
    projectMargin: 'G11',
    pureProcurement: 'G12',
    supplierCredit: 'G14',
    procurementPayment: 'G15',
    subcontracting: 'G16',
  },
  fields: [
    field('contractName', '合同名称', 'basic', 'text', true, '合同名称是什么？', ['B4']),
    field('contractAmountCny', '合同总额（CNY）', 'basic', 'amount', true, '合同总额是多少人民币？', ['B4']),
    field('gm1', '合同利润率（GM1）', 'basic', 'percentage', true, '项目 GM1 是多少？', ['B4']),
    field('customerName', '签约客户全称', 'basic', 'text', true, '签约客户全称是什么？', ['E4']),
    field('customerRating', '签约客户评级', 'basic', 'rating', true, '签约客户评级是什么？', ['E4']),
    field('customerCollectionHealth', '客户回款健康度', 'risk', 'number', true, '客户回款健康度是几级？'),
    field('endUserName', '最终用户全称', 'basic', 'text', true, '最终用户全称是什么？', ['E4']),
    field('hasProcurement', '是否涉及采购', 'risk', 'boolean', true, '项目是否涉及采购？'),
    field('supplierName', '供应商全称', 'basic', 'text', false, '供应商全称是什么？', ['E4'], procurementCondition),
    field('salesBu', '销售 BU', 'basic', 'text', true, '所属销售 BU 是什么？', ['G4']),
    field('salesRegion', '销售区域', 'basic', 'text', true, '销售区域是什么？', ['G4']),
    field('salesManager', '销售经理', 'basic', 'text', true, '销售经理是谁？', ['G4']),
    field('opportunitySerialNumber', '商机流水号', 'basic', 'text', false, '商机流水号是什么？', ['G4']),
    field('chainLevel', '签约链条层级', 'risk', 'text', true, '我司处于最终用户直签、一级分包还是更下级链条？'),
    field('upstreamSigned', '上游是否已签约', 'risk', 'boolean', true, '上游合同是否已经签署？'),
    field('fundingPartyConfirmed', '资金方是否明确', 'risk', 'boolean', true, '项目资金方是否已经明确？'),
    field('isBackToBackPayment', '是否背靠背付款', 'risk', 'boolean', true, '付款条款是否背靠背？'),
    field('isQualityWhitelistCustomer', '是否优质白名单客户', 'risk', 'boolean', true, '客户是否属于优质白名单？'),
    field('prepaymentPercent', '预付款比例', 'risk', 'percentage', false, '客户预付款比例是多少？'),
    field('hasChannelFee', '是否涉及渠道费用', 'risk', 'boolean', true, '项目是否涉及销售渠道费用？'),
    field('externalProcurementPercent', '外采成本占比', 'risk', 'percentage', false, '外采成本占项目成本的比例是多少？', [], procurementCondition),
    field('thirdPartyCoreDelivery', '第三方是否承担核心交付', 'risk', 'boolean', false, '第三方是否承担核心交付责任？', [], procurementCondition),
    field('supplierPaidInCapital', '供应商实缴资本', 'risk', 'amount', false, '供应商实缴资本是多少？', [], procurementCondition),
    field('procurementAmount', '采购金额', 'risk', 'amount', false, '本项目采购金额是多少？', [], procurementCondition),
    field('supplierEntityType', '供应商主体类型', 'risk', 'text', false, '供应商是公司还是个体工商户？', [], procurementCondition),
    field('supplierRating', '供应商评级', 'risk', 'rating', false, '供应商评级是什么？', [], procurementCondition),
    field('advanceProcurement', '是否提前采购', 'risk', 'boolean', false, '是否存在提前采购？', [], procurementCondition),
    field('hasFinancing', '是否存在垫资', 'risk', 'boolean', false, '项目是否存在直接或潜在垫资？', [], procurementCondition),
    field('directFinancingAmount', '直接垫资金额', 'risk', 'amount', false, '直接垫资金额是多少？', [], financingCondition),
    field('directFinancingMonths', '直接垫资期限（月）', 'risk', 'number', false, '直接垫资期限是几个月？', [], financingCondition),
    field('potentialFinancingAmount', '潜在垫资金额', 'risk', 'amount', false, '潜在垫资金额是多少？', [], financingCondition),
    field('allowsUnauthorizedSubcontracting', '是否允许未经许可二次分包', 'risk', 'boolean', false, '合同是否允许供应商未经许可再次分包？', [], procurementCondition),
    field('opportunitySource', '商机来源', 'project', 'text', true, '商机来自哪里？', ['E21'], undefined, GUIDANCE.D21),
    field('projectBackground', '项目背景及政策', 'project', 'text', true, '请说明项目背景和政策支持。', ['E22'], undefined, GUIDANCE.D22),
    field('contractChainProgress', '签约链条及签约进展', 'project', 'text', true, '请说明签约链条和当前签约进展。', ['E23'], undefined, GUIDANCE.D23),
    field('fundingStatus', '资金方及资金来源与落实情况', 'project', 'text', true, '请说明资金方、资金来源和落实情况。', ['E24'], undefined, GUIDANCE.D24),
    field('commercialTerms', '重要商务条款', 'project', 'text', true, '请说明提供内容、付款、验收和交付条款。', ['E25'], undefined, GUIDANCE.D25),
    field('amountMarginRecognition', '项目金额、利润及收入确认方法', 'project', 'text', true, '请说明金额、税率、毛利率和收入确认方法。', ['E26'], undefined, GUIDANCE.D26),
    field('procurementOverview', '采购类型、内容、原因及预算', 'procurement', 'text', false, '请说明采购类型、内容、原因和预算。', ['E27'], procurementCondition, GUIDANCE.D27),
    field('supplierOverview', '供应商情况说明', 'procurement', 'text', false, '请说明供应商资质和能力。', ['E28'], procurementCondition, GUIDANCE.D28),
    field('procurementTerms', '采购形式及重要商务条款', 'procurement', 'text', false, '请说明采购金额、方式和条款。', ['E29'], procurementCondition, GUIDANCE.D29),
    field('financingOverview', '垫资情况说明', 'procurement', 'text', false, '请说明垫资金额、成本、原因和上下游付款安排。', ['E30'], financingCondition, GUIDANCE.D30),
    field('strategicAlignment', '战略契合度', 'significance', 'text', true, '项目与公司战略如何契合？', ['E33']),
    field('productCapability', '公司产品能力', 'significance', 'text', true, '项目如何体现或拓展公司产品能力？', ['E34']),
    field('projectContinuity', '项目延续性', 'significance', 'text', true, '项目是否会带来延续性机会？', ['E35']),
    field('contractRiskControl', '签约风险管控', 'control', 'text', true, '针对签约风险有哪些管控措施？', ['E38']),
    field('deliveryRiskControl', '交付风险管控', 'control', 'text', true, '针对交付风险有哪些管控措施？', ['E39']),
    field('collectionRiskControl', '回款风险管控', 'control', 'text', true, '针对回款风险有哪些管控措施？', ['E40']),
    field('collectionCommitment', '回款承诺', 'commitment', 'text', false, '请给出回款时间承诺。', ['E43']),
    field('deliveryCommitment', '交付承诺', 'commitment', 'text', false, '请给出交付质量和时间承诺。', ['E44']),
    field('marginCommitment', '利润承诺', 'commitment', 'text', false, '请给出利润达标承诺。', ['E45']),
    field('supplierCommitment', '供应商承诺', 'commitment', 'text', false, '请给出供应商风控落实承诺。', ['E46'], procurementCondition),
    field('newOpportunityCommitment', '新商机承诺', 'commitment', 'text', false, '请说明衍生新项目承诺。', ['E47']),
    field('otherCommitment', '其他承诺', 'commitment', 'text', false, '是否还有其他承诺？', ['E48']),
  ],
};
